language: cpp

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
compiler:
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://download.qt.io/official_releases/qt/5.0/5.0.2/qt-linux-opensource-5.0.2-x86-offline.run && chmod +x ./qt-linux-opensource-5.0.2-x86-offline.run && sudo ./qt-linux-opensource-5.0.2-x86-offline.run && sudo apt-get update && sudo apt-get install libglu1-mesa-dev -y; fi 
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make

branches:
  only:
    - master

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#naturalgm"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"

os:
  - linux
  - osx
